### ISSUE TITLE
error.php not found

### ISSUE THREAD

**Issue by knkrth** [gmathis96/MailDud#1]
hi i got this Warning: include_once(site/controllers/error.php): failed to open stream: No such file or directory in /home/u739849512/public_html/mail/index.php on line 58

can you include error.php file on site folder

**Comment by gmathis96** [comment]
The error.php file is your own custom 404 page... Usually the only thing I have in that file is "404 Error" for any new projects.

**Comment by knkrth** [comment]
Thank you for your quick response.
